RAF: RAF.cxx Molecule.h Molecule.cxx Reaction.h Reaction.cxx ReacSet.h ReacSet.cxx
	g++ -o ../RAF RAF.cxx Molecule.cxx Reaction.cxx ReacSet.cxx

BPM: BinPolModel.cxx zipf.h zipf.c
	g++ -o ../BinPolModel BinPolModel.cxx zipf.c

clean:
	rm -f *~ *.o
